# external Dependencies Installation
- name: Install external dependency
  apt: 
    # ,libxmlsec1-dev
    name: [zlib1g-dev,libxml2-dev,libsqlite3-dev,libpq-dev]
    update_cache: yes
      
      





